// Rich font catalog for Fontally with typographic metadata, mood tags, and variable font support
export const ENRICHED_FONT_CATALOG = [
  // Sans-Serif
  {
    family: 'Inter',
    category: 'sans-serif',
    variants: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    is_variable: true,
    min_weight: 100,
    max_weight: 900,
    designer: 'Rasmus Andersson',
    popularity: 99,
    mood_tags: ['clean', 'neutral', 'tech', 'ui', 'modern', 'minimalist', 'swiss', 'readable'],
    description: 'A versatile neo-grotesque variable typeface crafted specifically for computer screens with tall x-height and micro-clarity.',
    use_cases: ['dashboard', 'saas', 'operating-system', 'mobile-app']
  },
  {
    family: 'Plus Jakarta Sans',
    category: 'sans-serif',
    variants: ['200', '300', '400', '500', '600', '700', '800'],
    is_variable: true,
    min_weight: 200,
    max_weight: 800,
    designer: 'Gumpita Rahayu',
    popularity: 95,
    mood_tags: ['modern', 'friendly', 'geometric', 'fintech', 'contemporary', 'startup'],
    description: 'A fresh modern geometric sans-serif with friendly curved terminals, highly popular for high-growth tech startups.',
    use_cases: ['fintech', 'landing-page', 'brand-identity']
  },
  {
    family: 'Roboto',
    category: 'sans-serif',
    variants: ['100', '300', '400', '500', '700', '900'],
    is_variable: true,
    min_weight: 100,
    max_weight: 900,
    designer: 'Christian Robertson',
    popularity: 98,
    mood_tags: ['mechanical', 'geometric', 'friendly', 'workhorse', 'modern'],
    description: 'Dual nature grotesque blending geometric forms with open, friendly curves for screen clarity.',
    use_cases: ['mobile', 'system', 'corporate']
  },
  {
    family: 'Montserrat',
    category: 'sans-serif',
    variants: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    is_variable: true,
    min_weight: 100,
    max_weight: 900,
    designer: 'Julieta Ulanovsky',
    popularity: 97,
    mood_tags: ['geometric', 'urban', 'posters', 'architecture', 'bold', 'punchy'],
    description: 'Inspired by traditional neighborhood signs in Buenos Aires, wide and commanding geometry.',
    use_cases: ['posters', 'headings', 'branding']
  },
  {
    family: 'Poppins',
    category: 'sans-serif',
    variants: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    is_variable: false,
    min_weight: 100,
    max_weight: 900,
    designer: 'Indian Type Foundry',
    popularity: 96,
    mood_tags: ['geometric', 'friendly', 'circular', 'warm', 'approachable'],
    description: 'Pure geometric circles and monoline strokes, highly approachable and warm.',
    use_cases: ['e-commerce', 'agency', 'consumer-app']
  },
  {
    family: 'Space Grotesk',
    category: 'sans-serif',
    variants: ['300', '400', '500', '600', '700'],
    is_variable: true,
    min_weight: 300,
    max_weight: 700,
    designer: 'Florian Karsten',
    popularity: 92,
    mood_tags: ['brutalist', 'quirky', 'crypto', 'web3', 'tech', 'developer', 'hacker'],
    description: 'Proportional sans-serif based on Space Mono, sharp idiosyncratic details, brutalist aesthetic.',
    use_cases: ['crypto', 'dev-tools', 'zine', 'design-portfolio']
  },
  {
    family: 'DM Sans',
    category: 'sans-serif',
    variants: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    is_variable: true,
    min_weight: 100,
    max_weight: 900,
    designer: 'Colophon Foundry',
    popularity: 94,
    mood_tags: ['low-contrast', 'geometric', 'clean', 'editorial', 'modern'],
    description: 'Precise low-contrast geometric sans intended for small screen readability and sharp headlines.',
    use_cases: ['editorial', 'fintech', 'minimalist-web']
  },
  {
    family: 'Outfit',
    category: 'sans-serif',
    variants: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    is_variable: true,
    min_weight: 100,
    max_weight: 900,
    designer: 'Rodrigo Fuenzalida',
    popularity: 91,
    mood_tags: ['geometric', 'clean', 'contemporary', 'brand', 'crisp'],
    description: 'Fashion-forward clean geometric display and text system.',
    use_cases: ['fashion', 'branding', 'technology']
  },
  {
    family: 'Manrope',
    category: 'sans-serif',
    variants: ['200', '300', '400', '500', '600', '700', '800'],
    is_variable: true,
    min_weight: 200,
    max_weight: 800,
    designer: 'Mikhail Sharanda',
    popularity: 90,
    mood_tags: ['modern', 'semi-condensed', 'fintech', 'ui', 'geometric'],
    description: 'Balanced modern grotesque with semi-rounded strokes and robust numerals.',
    use_cases: ['banking', 'analytics', 'software']
  },
  {
    family: 'Syne',
    category: 'sans-serif',
    variants: ['400', '500', '600', '700', '800'],
    is_variable: true,
    min_weight: 400,
    max_weight: 800,
    designer: 'Lucas Descroix',
    popularity: 88,
    mood_tags: ['avant-garde', 'experimental', 'fashion', 'ultra-wide', 'display', 'art'],
    description: 'Daring avant-garde typeface that stretches from sensible text to extreme ultra-wide display weights.',
    use_cases: ['art-direction', 'fashion-editorial', 'cultural-festivals']
  },
  {
    family: 'Unbounded',
    category: 'sans-serif',
    variants: ['300', '400', '500', '600', '700', '800', '900'],
    is_variable: true,
    min_weight: 300,
    max_weight: 900,
    designer: 'Studio Koto',
    popularity: 87,
    mood_tags: ['futuristic', 'heavy', 'display', 'gaming', 'bold', 'extended'],
    description: 'Wide, punchy, uninhibited geometric sans tailored for high-impact brand statements.',
    use_cases: ['gaming', 'music', 'brand-campaign']
  },
  {
    family: 'Bricolage Grotesque',
    category: 'sans-serif',
    variants: ['200', '300', '400', '500', '600', '700', '800'],
    is_variable: true,
    min_weight: 200,
    max_weight: 800,
    designer: 'Mathieu Triay',
    popularity: 89,
    mood_tags: ['retro', 'warm', 'expressive', 'french-grotesque', 'eclectic', 'humanist'],
    description: 'Collage of historical British and French grotesque traits, rich in personality and visual rhythm.',
    use_cases: ['editorial', 'craft-brand', 'creative-portfolio']
  },
  {
    family: 'Work Sans',
    category: 'sans-serif',
    variants: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    is_variable: true,
    min_weight: 100,
    max_weight: 900,
    designer: 'Wei Huang',
    popularity: 93,
    mood_tags: ['early-grotesque', 'humanist', 'screen-first', 'print', 'structured'],
    description: 'Based on early 19th-century grots, highly functional for both screen reading and dense prints.',
    use_cases: ['publishing', 'workspace-apps', 'architecture']
  },

  // Serif
  {
    family: 'Playfair Display',
    category: 'serif',
    variants: ['400', '500', '600', '700', '800', '900', 'italic'],
    is_variable: true,
    min_weight: 400,
    max_weight: 900,
    designer: 'Claus Eggers Sørensen',
    popularity: 98,
    mood_tags: ['luxury', 'editorial', 'classic', 'high-contrast', 'transitional', 'dramatic'],
    description: 'High-contrast transitional serif drawing inspiration from Enlightenment-era Baskerville letterforms.',
    use_cases: ['luxury-brand', 'fashion-magazine', 'fine-dining', 'hospitality']
  },
  {
    family: 'Lora',
    category: 'serif',
    variants: ['400', '500', '600', '700', 'italic'],
    is_variable: true,
    min_weight: 400,
    max_weight: 700,
    designer: 'Cyreal',
    popularity: 96,
    mood_tags: ['literary', 'calligraphic', 'contemporary', 'reading', 'warm', 'gentle'],
    description: 'Contemporary serif with brushed calligraphic roots, perfect for long-form essays and storytelling.',
    use_cases: ['blog', 'news', 'literary-journal']
  },
  {
    family: 'Cormorant Garamond',
    category: 'serif',
    variants: ['300', '400', '500', '600', '700', 'italic'],
    is_variable: true,
    min_weight: 300,
    max_weight: 700,
    designer: 'Christian Thalmann',
    popularity: 94,
    mood_tags: ['delicate', 'aristocratic', 'quiet-luxury', 'renaissance', 'sharp', 'classical'],
    description: 'Exquisite revival of Claude Garamond’s sixteenth-century typography, razor-sharp counters.',
    use_cases: ['luxury-perfume', 'art-catalog', 'poetry-book']
  },
  {
    family: 'Fraunces',
    category: 'serif',
    variants: ['100', '200', '300', '400', '500', '600', '700', '800', '900', 'italic'],
    is_variable: true,
    min_weight: 100,
    max_weight: 900,
    designer: 'Phaedra Charles, Flavia Zimbardi',
    popularity: 92,
    mood_tags: ['wonky', 'soft', 'vintage', 'warm', 'editorial', 'curvy', '70s'],
    description: 'Warm, tactile "wonky" serif with variable optical size, softness, and dramatic oldstyle gestures.',
    use_cases: ['bakery', 'organic-goods', 'craft-brewery', 'boutique']
  },
  {
    family: 'Instrument Serif',
    category: 'serif',
    variants: ['400', 'italic'],
    is_variable: false,
    min_weight: 400,
    max_weight: 400,
    designer: 'Instrument, Jordan Bell',
    popularity: 91,
    mood_tags: ['quiet-luxury', 'contemporary', 'poetic', 'refined', 'curated', 'minimalist'],
    description: 'Contemporary high-fashion editorial serif with expressive italic gestures and understated confidence.',
    use_cases: ['design-studio', 'lookbook', 'high-end-interior']
  },
  {
    family: 'Cinzel',
    category: 'serif',
    variants: ['400', '500', '600', '700', '800', '900'],
    is_variable: true,
    min_weight: 400,
    max_weight: 900,
    designer: 'Natanael Gama',
    popularity: 93,
    mood_tags: ['monumental', 'roman', 'cinematic', 'imperial', 'history', 'majestic'],
    description: 'All-caps inspired by classical Roman inscriptions, widely used in film titles and heritage brands.',
    use_cases: ['film-poster', 'fantasy-game', 'estate-wine']
  },
  {
    family: 'EB Garamond',
    category: 'serif',
    variants: ['400', '500', '600', '700', '800', 'italic'],
    is_variable: true,
    min_weight: 400,
    max_weight: 800,
    designer: 'Georg Duffner',
    popularity: 90,
    mood_tags: ['scholarly', 'renaissance', 'humanist', 'academic', 'literature'],
    description: 'Community-driven historical digital engraving of Claude Garamond’s legendary roman.',
    use_cases: ['academic-paper', 'novel', 'historical-archive']
  },
  {
    family: 'Bodoni Moda',
    category: 'serif',
    variants: ['400', '500', '600', '700', '800', '900', 'italic'],
    is_variable: true,
    min_weight: 400,
    max_weight: 900,
    designer: 'Owen Earl',
    popularity: 88,
    mood_tags: ['haute-couture', 'italian', 'didone', 'dramatic', 'fashion', 'vogue'],
    description: 'High-contrast modern Didone serif tailored for runway fashion, high jewelry, and glamor.',
    use_cases: ['vogue-style', 'perfume-brand', 'jewelry']
  },
  {
    family: 'Newsreader',
    category: 'serif',
    variants: ['200', '300', '400', '500', '600', '700', '800', 'italic'],
    is_variable: true,
    min_weight: 200,
    max_weight: 800,
    designer: 'Production Type',
    popularity: 87,
    mood_tags: ['editorial', 'journalism', 'continuous-reading', 'authoritative', 'literary'],
    description: 'Commissioned for long-form on-screen reading, authoritative journalistic precision.',
    use_cases: ['investigative-journal', 'ebook', 'thought-leadership']
  },

  // Display
  {
    family: 'Righteous',
    category: 'display',
    variants: ['400'],
    is_variable: false,
    min_weight: 400,
    max_weight: 400,
    designer: 'Astigmatic',
    popularity: 89,
    mood_tags: ['retro-futurism', 'art-deco', 'sci-fi', 'neon', '80s', 'arcade'],
    description: 'Deco-inspired retro-futuristic grid display with geometric rounded turns.',
    use_cases: ['synthwave-album', 'gaming-channel', 'retro-poster']
  },
  {
    family: 'Shrikhand',
    category: 'display',
    variants: ['400'],
    is_variable: false,
    min_weight: 400,
    max_weight: 400,
    designer: 'Jonny Pinhorn',
    popularity: 88,
    mood_tags: ['bold', 'colorful', 'curvy', 'indian-street-handpainted', 'loud', 'festive'],
    description: 'Expansive voluptuous display inspired by hand-painted Gujarati street graphics.',
    use_cases: ['street-food', 'festival-branding', 'quirky-packaging']
  },
  {
    family: 'Monoton',
    category: 'display',
    variants: ['400'],
    is_variable: false,
    min_weight: 400,
    max_weight: 400,
    designer: 'Vernon Adams',
    popularity: 86,
    mood_tags: ['disco', 'multiline', '70s', 'neon', 'striated', 'dramatic'],
    description: 'Striated multi-line display evoking seventies discotheque marquees and neon signs.',
    use_cases: ['club-poster', 'vinyl-sleeve', 'cocktail-bar']
  },
  {
    family: 'Bebas Neue',
    category: 'display',
    variants: ['400'],
    is_variable: false,
    min_weight: 400,
    max_weight: 400,
    designer: 'Ryoichi Tsunekawa',
    popularity: 97,
    mood_tags: ['bold', 'all-caps', 'condensed', 'athletic', 'punchy', 'action'],
    description: 'The heavyweight king of condensed capitals, commanding immediate visual hierarchy.',
    use_cases: ['sports-brand', 'youtube-thumbnail', 'action-film']
  },
  {
    family: 'Oswald',
    category: 'sans-serif',
    variants: ['200', '300', '400', '500', '600', '700'],
    is_variable: true,
    min_weight: 200,
    max_weight: 700,
    designer: 'Vernon Adams',
    popularity: 95,
    mood_tags: ['condensed', 'industrial', 'signage', 'strong', 'headline'],
    description: 'Reworking of classic Alternate Gothic for digital screens, compact and punchy.',
    use_cases: ['news-ticker', 'banner', 'fitness']
  },
  {
    family: 'Press Start 2P',
    category: 'display',
    variants: ['400'],
    is_variable: false,
    min_weight: 400,
    max_weight: 400,
    designer: 'CodeMan38',
    popularity: 87,
    mood_tags: ['8-bit', 'pixel', 'retro-gaming', 'arcade', 'nes', 'nostalgia'],
    description: 'Authentic 1980s arcade pixel typography rendered with uncompromising 8-bit geometry.',
    use_cases: ['indie-game', 'retro-tech', 'pixel-art']
  },
  {
    family: 'Orbitron',
    category: 'display',
    variants: ['400', '500', '600', '700', '800', '900'],
    is_variable: true,
    min_weight: 400,
    max_weight: 900,
    designer: 'Matt McInerney',
    popularity: 88,
    mood_tags: ['sci-fi', 'cyberpunk', 'aerospace', 'hud', 'futuristic'],
    description: 'Geometric sans specifically crafted for sci-fi user interfaces and planetary spacecraft.',
    use_cases: ['space-mission', 'hud-display', 'cyberpunk-game']
  },

  // Monospace
  {
    family: 'Space Mono',
    category: 'monospace',
    variants: ['400', '700', 'italic'],
    is_variable: false,
    min_weight: 400,
    max_weight: 700,
    designer: 'Colophon Foundry',
    popularity: 92,
    mood_tags: ['developer', 'brutalist', 'code', 'space-age', 'retro-tech', 'editorial'],
    description: 'Fixed-width geometric display grotesque combining 1960s headline punch with terminal grid.',
    use_cases: ['developer-tool', 'zine', 'terminal', 'tech-manifesto']
  },
  {
    family: 'JetBrains Mono',
    category: 'monospace',
    variants: ['100', '200', '300', '400', '500', '600', '700', '800', 'italic'],
    is_variable: true,
    min_weight: 100,
    max_weight: 800,
    designer: 'Philipp Nurullin, Konstantin Bulenkov',
    popularity: 94,
    mood_tags: ['coding', 'ligatures', 'ergonomic', 'developer', 'clean', 'terminal'],
    description: 'Engineered specifically for programming with increased letter height, crisp ligatures, and eye-relief.',
    use_cases: ['code-editor', 'technical-docs', 'syntax-theme']
  },
  {
    family: 'Fira Code',
    category: 'monospace',
    variants: ['300', '400', '500', '600', '700'],
    is_variable: true,
    min_weight: 300,
    max_weight: 700,
    designer: 'Nikita Prokopov',
    popularity: 93,
    mood_tags: ['ligatures', 'coding', 'modern', 'hacker', 'ascii'],
    description: 'Monospaced font containing programming ligatures that transform common symbol combinations into single glyphs.',
    use_cases: ['ide', 'engineering-blog', 'terminal']
  },
  {
    family: 'DM Mono',
    category: 'monospace',
    variants: ['300', '400', '500', 'italic'],
    is_variable: false,
    min_weight: 300,
    max_weight: 500,
    designer: 'Colophon Foundry',
    popularity: 88,
    mood_tags: ['clean', 'neutral', 'refined', 'tech-editorial', 'balanced'],
    description: 'Understated, elegantly proportioned monospaced typeface for subtle data tables and code accents.',
    use_cases: ['financial-data', 'receipts', 'design-spec']
  },
  {
    family: 'VT323',
    category: 'monospace',
    variants: ['400'],
    is_variable: false,
    min_weight: 400,
    max_weight: 400,
    designer: 'Peter Hull',
    popularity: 85,
    mood_tags: ['crt', 'retro', 'terminal', 'dec-vt220', 'green-screen', 'vintage'],
    description: 'Simulates the iconic DEC VT220 phosphor green CRT terminal screen glyphs from 1983.',
    use_cases: ['cli-interface', 'retro-adventure', 'hacker-screen']
  },

  // Handwriting / Script
  {
    family: 'Sacramento',
    category: 'handwriting',
    variants: ['400'],
    is_variable: false,
    min_weight: 400,
    max_weight: 400,
    designer: 'Astigmatic',
    popularity: 86,
    mood_tags: ['monoline', 'casual', '50s', 'script', 'invitation', 'delicate'],
    description: 'Semiconnected monoline script drawing from mid-century hand-lettered promotional art.',
    use_cases: ['wedding-stationery', 'bakery-logo', 'handcrafted-soaps']
  },
  {
    family: 'Caveat',
    category: 'handwriting',
    variants: ['400', '500', '600', '700'],
    is_variable: true,
    min_weight: 400,
    max_weight: 700,
    designer: 'Pablo Impallari',
    popularity: 91,
    mood_tags: ['handwritten', 'casual', 'note', 'friendly', 'journal', 'organic'],
    description: 'Fluid natural pen handwriting designed to look like personal notes and annotations.',
    use_cases: ['sticky-notes', 'personal-blog', 'informal-quotes']
  },
  {
    family: 'Pacifico',
    category: 'handwriting',
    variants: ['400'],
    is_variable: false,
    min_weight: 400,
    max_weight: 400,
    designer: 'Vernon Adams',
    popularity: 92,
    mood_tags: ['surf', 'california', 'beach', 'retro-script', 'brush', 'fun'],
    description: 'Original brush script inspired by 1950s American surf culture and beach signs.',
    use_cases: ['surfwear', 'smoothie-bar', 'ice-cream-shop']
  },
  {
    family: 'Dancing Script',
    category: 'handwriting',
    variants: ['400', '500', '600', '700'],
    is_variable: true,
    min_weight: 400,
    max_weight: 700,
    designer: 'Pablo Impallari',
    popularity: 90,
    mood_tags: ['bouncy', 'lively', 'casual', 'friendly', 'script'],
    description: 'Lively informal script with bouncing baseline and letters changing size dynamically.',
    use_cases: ['greetings', 'boutique', 'casual-packaging']
  },
  {
    family: 'Pinyon Script',
    category: 'handwriting',
    variants: ['400'],
    is_variable: false,
    min_weight: 400,
    max_weight: 400,
    designer: 'Nicole Fally',
    popularity: 87,
    mood_tags: ['calligraphy', 'copperplate', 'swashes', 'formal', 'aristocratic', 'romantic'],
    description: 'Romantic French round-hand script with dramatic curved swashes and luxury flair.',
    use_cases: ['invitation', 'luxury-champagne', 'château']
  }
]

// Map by lowercase family for O(1) lookup
export const FONT_MAP = new Map(
  ENRICHED_FONT_CATALOG.map((f) => [f.family.toLowerCase(), f])
)
